name: Laravel

on:
  push:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    services:
      # mysql-service Label used to access the service container
      mysql-service:
        # Docker Hub image (also with version)
        image: mysql:5.7
        env:
          ## Accessing to Github secrets, where you can store your configuration
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run:  mysql -h 127.0.0.1 --port 33306 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS db_test;'
    - name: Run migrations
      run: php artisan migrate --force
   # - name: Create Database
   #   run: |
   #     mkdir -p database
   #     touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: db_test
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_USER: root
      run: vendor/bin/phpunit
      
      
    # print branch name
    - name: Get branch name
      id: branch_name
      run: echo "::set-output name=branch::${GITHUB_REF##*/}"

    - name: Deploy to production
      env:
        PUSHED_BRANCH_NAME: ${{steps.branch_name.outputs.branch}}
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: 178.128.48.244
        envs: PUSHED_BRANCH_NAME
        password: ${{ secrets.SSH_PASS }}
        script: /home/aqib/server_deploy.sh $PUSHED_BRANCH_NAME
