name: Laravel

on:
  push:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
      
      
    # print branch name
    - name: Get branch name
      id: branch_name
      run: echo "::set-output name=branch::${GITHUB_REF##*/}"

    - name: Deploy to production
      env:
        PUSHED_BRANCH_NAME: ${{steps.branch_name.outputs.branch}}
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: 178.128.48.244
        envs: PUSHED_BRANCH_NAME
        password: ${{ secrets.SSH_PASS }}
        script: /home/aqib/server_deploy.sh $PUSHED_BRANCH_NAME
